baseURL                = "https://3234663254wz-dev.github.io/"
locale                  = "en-us"
title                   = "METEOR"
theme                   = "hugo-theme-stack"
defaultContentLanguage  = "en"
hasCJKLanguage          = true

[pagination]
    pagerSize = 10

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = ""
