baseURL                = "https://METEOR-ECHO.github.io/"
locale                  = "zh-cn"
title                   = "METEOR"
theme                   = "hugo-theme-stack"
defaultContentLanguage  = "zh"
hasCJKLanguage          = true

[pagination]
    pagerSize = 10

[permalinks]
    post = "/p/:slug/"
    page = "/:slug/"

[services.disqus]
    shortname = ""
