[zh]
    label   = "简体中文"
    title   = "METEOR"
    weight  = 1

    [zh.params.sidebar]
        subtitle = "一个关于技术与生活的个人博客"

[en]
    label   = "English"
    title   = "METEOR"
    weight  = 2

    [en.params.sidebar]
        subtitle = "A personal blog about tech and life"
